<?= $this->doctype() ?>
<html>
<head>
    
	<?= $this->headTitle($this->translate('Personal Sushi - Administration')) ?>

	<meta charset="utf-8" />
	<?=
		$this
		->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0')
		->appendName('apple-mobile-web-app-capable', 'yes')
		->appendName('apple-mobile-web-app-status-bar-style', 'black')
	?>

	<?=
		$this
		->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

		->appendStylesheet($this->basePath() . '/css/application.css')
	?>



</head>
<body class="background-dark">
<?= $this->adminFlashMessenger()->render('error', array('text-center')) ?>
<?= $this->adminFlashMessenger()->render('default', array('text-center')) ?>
<?= $this->adminFlashMessenger()->render('info', array('text-center')) ?>
<?= $this->adminFlashMessenger()->render('success', array('text-center')) ?>
<div class="logo">
    <h4><a href="index.html">Light <strong>Blue</strong></a></h4>
</div>

<?= $this->navigation('Admin\Navigation')->menu()->setPartial(array('helper/navigation/admin.phtml', 'Admin'))->render() ?>

<div class="wrap">

    <header class="page-header">
        <div class="navbar">
            <ul class="nav navbar-nav navbar-right pull-right">
                <li class="hidden-xs">
                    <a href="#" id="settings"
                       title="<?= $this->translate('Settings') ?>"
                       data-toggle="popover"
                       data-placement="bottom">
                        <i class="fa fa-cog"></i>
                    </a>
                </li>
                <li class="hidden-xs dropdown">
                    <a href="#" title="<?= $this->translate('Account') ?>" id="account"
                       class="dropdown-toggle"
                       data-toggle="dropdown">
                        <i class="fa fa-user"></i>
                    </a>
                    <ul id="account-menu" class="dropdown-menu account" role="menu">
                        <li role="presentation" class="account-picture">
                            <?= $this->loggedAdmin()->getFullname() ?>
                        </li>
                        <li role="presentation">
                            <a href="<?= $this->url('admin', ['controller' => 'admin', 'action' => 'account']) ?>" class="link">
                                <i class="fa fa-user"></i>
                                <?= $this->translate('My Account') ?>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="visible-xs">
                    <a href="#"
                       class="btn-navbar"
                       data-toggle="collapse"
                       data-target=".sidebar"
                       title="">
                        <i class="fa fa-bars"></i>
                    </a>
                </li>
                <li class="hidden-xs"><a href="<?= $this->url('admin', ['controller' => 'auth', 'action' => 'logout']) ?>"><i class="fa fa-sign-out"></i></a></li>
            </ul>
        </div>
    </header>

    <div class="content container">
    
	   <?= $this->content ?>

    </div>

</div>

<?=
	$this
	->headScript()

	//JQuery 2.0.3
	->appendFile($this->basePath() . '/lib/jquery/jquery-2.0.3.min.js')
    ->appendFile($this->basePath() . '/lib/jquery-maskedinput/jquery.maskedinput.js')
    ->appendFile($this->basePath() . '/lib/parsley/parsley.js')
	->appendFile($this->basePath() . '/lib/icheck.js/jquery.icheck.js')
    ->appendFile($this->basePath() . '/lib/select2.js')
    ->appendFile($this->basePath() . '/lib/jquery.autogrow-textarea.js')
	->appendFile($this->basePath() . '/lib/sparkline/jquery.sparkline.js')
	->appendFile($this->basePath() . '/lib/jquery-ui-1.10.3.custom.js')
	->appendFile($this->basePath() . '/lib/jquery.slimscroll.js')
    ->appendFile($this->basePath() . '/lib/jquery.nestable.js')
    ->appendFile($this->basePath() . '/lib/spin.js/spin.min.js')
    ->appendFile($this->basePath() . '/lib/ladda/ladda.min.js')
    ->appendFile($this->basePath() . '/lib/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/lib/jquery.cookie.js')

	->appendFile($this->basePath() . '/lib/nvd3/lib/d3.v2.js')
	->appendFile($this->basePath() . '/lib/nvd3/nv.d3.custom.js')
	->appendFile($this->basePath() . '/lib/nvd3/src/models/scatter.js')
	->appendFile($this->basePath() . '/lib/nvd3/src/models/axis.js')
	->appendFile($this->basePath() . '/lib/nvd3/src/models/legend.js')
    ->appendFile($this->basePath() . '/lib/nvd3/src/models/stackedArea.js')
    ->appendFile($this->basePath() . '/lib/nvd3/src/models/stackedAreaChart.js')
	->appendFile($this->basePath() . '/lib/nvd3/src/models/line.js')
	->appendFile($this->basePath() . '/lib/nvd3/src/models/lineChart.js')
	->appendFile($this->basePath() . '/lib/nvd3/stream_layers.js')

	->appendFile($this->basePath() . '/lib/backbone/underscore-min.js')
	->appendFile($this->basePath() . '/lib/backbone/backbone-min.js')
	->appendFile($this->basePath() . '/lib/backbone/backbone.localStorage-min.js')

	->appendFile($this->basePath() . '/lib/bootstrap/transition.js')
	->appendFile($this->basePath() . '/lib/bootstrap/collapse.js')
	->appendFile($this->basePath() . '/lib/bootstrap/alert.js')
	->appendFile($this->basePath() . '/lib/bootstrap/tooltip.js')
	->appendFile($this->basePath() . '/lib/bootstrap/popover.js')
	->appendFile($this->basePath() . '/lib/bootstrap/button.js')
	->appendFile($this->basePath() . '/lib/bootstrap/tab.js')
	->appendFile($this->basePath() . '/lib/bootstrap/dropdown.js')
    ->appendFile($this->basePath() . '/lib/bootstrap/modal.js')

    ->appendFile($this->basePath() . '/lib/bootstrap-datepicker.js')
    ->appendFile($this->basePath() . '/lib/bootstrap-select/bootstrap-select.js')
    ->appendFile($this->basePath() . '/lib/wysihtml5/wysihtml5-0.3.0_rc2.js')
    ->appendFile($this->basePath() . '/lib/bootstrap-wysihtml5/bootstrap-wysihtml5.js')
    ->appendFile($this->basePath() . '/lib/bootstrap-switch.js')
    ->appendFile($this->basePath() . '/lib/bootstrap-colorpicker.js')
    ->appendFile($this->basePath() . '/lib/bootstrap-dialog/bootstrap-dialog.js')

    ->appendFile($this->basePath() . '/js/app.js')
    ->appendFile($this->basePath() . '/js/settings.js')
    ->appendFile($this->basePath() . '/js/index.js')
    ->appendFile($this->basePath() . '/js/chat.js')
    ->appendFile($this->basePath() . '/js/forms-elements.js')
    ->appendFile($this->basePath() . '/js/list-groups.js')
    ->appendFile($this->basePath() . '/js/flash-messenger.js')
    ->appendFile($this->basePath() . '/js/tables-dynamic.js');

?>

<?= $this->inlineScript() ?>

<script type="text/template" id="message-template">
        <div class="sender pull-left">
            <div class="icon">
                <img src="img/2.jpg" class="img-circle" alt="">
            </div>
            <div class="time">
                just now
            </div>
        </div>
        <div class="chat-message-body">
            <span class="arrow"></span>
            <div class="sender">Tikhon Laninga</div>
            <div class="text">
                <%- text %>
            </div>
        </div>
</script>

<script type="text/template" id="settings-template">
    <div class="setting clearfix">
        <div>Background</div>
        <div id="background-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% dark = background == 'dark'; light = background == 'light';%>
            <button type="button" data-value="dark" class="btn btn-sm btn-transparent <%= dark? 'active' : '' %>">Dark</button>
            <button type="button" data-value="light" class="btn btn-sm btn-transparent <%= light? 'active' : '' %>">Light</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar on the</div>
        <div id="sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% onRight = sidebar == 'right'%>
            <button type="button" data-value="left" class="btn btn-sm btn-transparent <%= onRight? '' : 'active' %>">Left</button>
            <button type="button" data-value="right" class="btn btn-sm btn-transparent <%= onRight? 'active' : '' %>">Right</button>
        </div>
    </div>
    <div class="setting clearfix">
        <div>Sidebar</div>
        <div id="display-sidebar-toggle" class="pull-left btn-group" data-toggle="buttons-radio">
            <% display = displaySidebar%>
            <button type="button" data-value="true" class="btn btn-sm btn-transparent <%= display? 'active' : '' %>">Show</button>
            <button type="button" data-value="false" class="btn btn-sm btn-transparent <%= display? '' : 'active' %>">Hide</button>
        </div>
    </div>
</script>

<script type="text/template" id="sidebar-settings-template">
    <% auto = sidebarState == 'auto'%>
    <% if (auto) {%>
    <button type="button"
            data-value="icons"
            class="btn-icons btn btn-transparent btn-sm">Icons</button>
    <button type="button"
            data-value="auto"
            class="btn-auto btn btn-transparent btn-sm">Auto</button>
    <%} else {%>
    <button type="button"
            data-value="auto"
            class="btn btn-transparent btn-sm">Auto</button>
    <% } %>
</script>

</body>
</html>