<?= $this->doctype() ?>
<html>
<head>

    <?= $this->headTitle('ZF2 Login ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <meta charset="utf-8" />
    <?=
        $this
        ->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0')
        ->appendName('apple-mobile-web-app-capable', 'yes')
        ->appendName('apple-mobile-web-app-status-bar-style', 'black')
    ?>

    <?=
        $this
        ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

        ->appendStylesheet($this->basePath() . '/css/application.min.css')
    ?>

    <?=
        $this
        ->headScript()

        ->appendFile($this->basePath() . '/lib/jquery/jquery-2.0.3.min.js')
        ->appendFile($this->basePath() . '/lib/backbone/underscore-min.js')
        ->appendFile($this->basePath() . '/js/settings.js');

    ?>

</head>
<body>
<?= $this->adminFlashMessenger()->render('error', array('text-center')) ?>
<?= $this->adminFlashMessenger()->render('success', array('text-center')) ?>
<div class="single-widget-container">
    <section class="widget login-widget">
        <header class="text-align-center">
            <h4><?= $this->translate('Administrator Login') ?></h4>
        </header>
        <div class="body">
        
            <?= $this->content ?>

        </div>
        <footer>
            <!--<div class="facebook-login">
                <a href="index.html"><span><i class="fa fa-facebook-square fa-lg"></i> LogIn with Facebook</span></a>
            </div>-->
        </footer>
    </section>
</div>
</body>
</html>