<?php

$formLabel = $this->plugin('formLabel');

$inputErrorClass = $this->element->getMessages() ? 'error ' : '';
$this->element->setAttribute( 'class', 'form-control ' . $inputErrorClass . $this->element->getAttribute('class') );

?>

<div class="element">

	<div class="label">

		<?= $formLabel->openTag( $labelAttributes ) . $this->label . $formLabel->closeTag() ?>

	</div>

    <div class="input">

    	<?= $this->formElement($this->element) ?>

    	<?php if($this->renderErrors): ?>

			<?=

				$this	
						->formElementErrors()
		                ->setMessageOpenFormat('<ul class="error-list"><li>')
		                ->setMessageSeparatorString('</li><li>')
		                ->setMessageCloseString('</ul>')
		                ->render($this->element)

			?>

		<?php endif ?>