<?php

$formLabel = $this->plugin('formLabel');

//Add class to label
$labelAttributes = array_merge( (array) $this->element->getLabelAttributes(), array('class' => 'checkbox') );

//Add class to input
$this->element->setAttribute( 'class', 'iCheck ' . $this->element->getAttribute('class') );

?>

<div class="control-group">
	<!-- @TODO decide where the label should be (see form_elements.html in the layout directory) -->
    <div class="controls form-group">

    	<?= $formLabel->openTag( $labelAttributes ) ?>

    		<?= $this->formElement($this->element) ?>

    	<?= $this->label . $formLabel->closeTag() ?>

    </div>

</div>